org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=true

minecraft_version=26.3
loader_version=0.19.5
loom_version=1.17.19
fabric_api_version=0.161.0+26.3
trinkets_version=4.2.1+26.3
tomlj_version=1.1.1
antlr_version=4.11.1
junit_version=6.1.0

mod_version=1.1.1
maven_group=dev.teartag
archives_base_name=teartag
